name: value_stories_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  # purchases_flutter: 
  # change_app_package_name:

  provider: ^6.0.2                         #USED FOR STATE MANAGEMENT IN OUR APP
  dots_indicator: ^2.0.0                    #USED FOR  THE WORM DESIGN LIKE INDICATOR  
  smooth_page_indicator: ^1.0.0+2
  # flutter_html:
  simple_html_css: ^3.0.1+1
  # flutter_rating_bar: ^3.0.1+1            #USED FOR RATING STARS
  # modal_progress_hud_nsn: 0.1.0-nullsafety-1              #USED FOR ASYNCHRONOUS PURPOSES

  
  # firebase_database: ^6.0.0
#   firebase_auth: ^0.18.1+2
#   firebase_crashlytics: ^0.2.1+1
  cloud_firestore: ^3.1.6
  # image_picker: ^0.8.0+1
  # image_crop: ^0.4.0
  # image_cropper: ^1.3.1
  # tflite: ^1.1.2
  # crop_your_image: ^0.5.1+1
#   dio: ^3.0.10
#   dio_http_cache: ^0.2.11
  get: ^4.6.1 
  get_it: ^7.2.0 
  fluid_bottom_nav_bar: ^1.3.0
  flutter_screenutil: ^5.1.0
  avatar_glow: ^2.0.2
  flutter_spinkit: ^5.1.0
  in_app_purchase: ^2.0.1 
  image_picker: ^0.8.4+4
  file_picker: ^4.3.2
  cached_network_image: ^3.2.0
  just_audio: ^0.9.18
  audio_video_progress_bar: ^0.10.0
    
  # audioplayers:
    

    
  #Backend plugins
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  shared_preferences: ^2.0.12
  firebase_core: ^1.11.0  



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/static_assets/
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600

    - family: Leiko
      fonts:
        - asset: assets/fonts/Leiko-Regular.otf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
